[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "qonsole"
version = "2.0.0"
readme = "README.md"
authors = [
    {name = "Jacob Williams", email = "jacobwilliams@users.noreply.github.com"}
]
description = "Light-weight python interpreter, easy to embed into Qt applications"
requires-python = ">=3.9,<4.0"
keywords = ["interactive", "interpreter", "console", "shell", "autocompletion", "jedi", "qt"]
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Environment :: X11 Applications :: Qt",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Interpreters",
    "Topic :: Software Development :: User Interfaces",
]
dependencies = [
    "qtpy",
    "jedi",
    "pygments",
    "ipython-pygments-lexers",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "hatch",
    "pytest",
    "pytest-cov",
    "pytest-qt",
]

[project.urls]
Homepage = "https://github.com/jacobwilliams/qonsole"

[tool.hatch.build.targets.wheel]
packages = ["qonsole"]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle
    "F",  # Pyflakes
    "UP",  # pyupgrade
    "B",  # flake8-bugbear
    "SIM",  # flake8-simplify
    "I",  # isort
]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]

[tool.pixi.pypi-dependencies]
qonsole = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }

[tool.pixi.tasks]

[tool.pixi.dependencies]
pyside6 = ">=6.11.0,<7"
gevent = ">=25.9.1,<26"
hatch = ">=1.16.5,<2"
ruff = ">=0.15.9,<0.16"
qtpy = ">=2.4.3,<3"
jedi = ">=0.19.2,<0.20"
pygments = ">=2.20.0,<3"
ipython_pygments_lexers = ">=1.1.1,<2"
pytest = ">=9.0.2,<10"
pytest-qt = ">=4.5.0,<5"
